Import("libcomputer")
Import("libparticles")
Import("libjsonc")
Import("libsimulator")
Import("outerEnv")

env = outerEnv.Clone()
env.AppendUnique(FRAMEWORKS = ["OpenCL"])

simulator = env.Program("simulator", Glob("*.c"),
                        LIBS = ["computer", "particles", "jsonc", "simulator"])
Depends(simulator, libcomputer)
Depends(simulator, libparticles)
Depends(simulator, libjsonc)
Depends(simulator, libsimulator)

Return("simulator")