VariantDir('build', '.', duplicate=0)

env = Environment(CCFLAGS="--std=c99 -g")
env.AppendUnique(FRAMEWORKS=Split('OpenCL'))

libsimulator = SConscript('build/libsimulator/SConscript', 'env')
simulator = SConscript('build/SConscript', 'env libsimulator')