import os

VariantDir('build', '.', duplicate=0)

env = Environment(CC="clang", CCFLAGS="--std=c99 -O4 -Wall -Werror")
env.AppendUnique(FRAMEWORKS=['OpenCL'])

libsimulator = SConscript('build/libsimulator/SConscript', 'env')
simulator = SConscript('build/SConscript', 'env libsimulator')