Import("libcomputer")
Import("outerEnv")

env = outerEnv.Clone()
env.AppendUnique(FRAMEWORKS = ["OpenCL"])

libsimulator = env.SharedLibrary("simulator", Glob("*.c"), LIBS=["computer"])
Depends(libsimulator, libcomputer)

Return("libsimulator")