Import("outerEnv")

env = outerEnv.Clone(CCFLAGS="--std=c99 -O4 -Wall -Werror")
env.AppendUnique(FRAMEWORKS=["OpenCL"])

libsimulator = env.SharedLibrary("simulator", Glob("*.c"))

Return("libsimulator")