Import("libjsonc")
Import("outerEnv")

env = outerEnv.Clone()
env.AppendUnique(FRAMEWORKS = ["OpenCL"])

libparticles = env.SharedLibrary("particles", Glob("*.c"), LIBS = ["jsonc"])
Depends(libparticles, libjsonc)

Return("libparticles")