from Build.macosx import TOOL_BUNDLE

Import("outerEnv")

env = outerEnv.Clone(CC="clang", CCFLAGS="--std=c99 -O4 -Wall -Werror -fobjc-gc")
env.AppendUnique(FRAMEWORKS=['OpenCL','Cocoa','AppKit','Foundation', 'BWToolkitFramework'], FRAMEWORKPATH=['External/BWToolkit/'])
TOOL_BUNDLE(env)

interpolator = env.Program("Interpolator", Glob("*.[cm]"))

env.MakeBundle("Interpolator.app", "Interpolator", "com.hortont.interpolator", "Interpolator-Info.plist", "APPL", resources=["MainMenu.xib"], frameworks=["../../External/BWToolkit/BWToolkitFramework.framework"])

Return("interpolator")