Import("outerEnv")

env = outerEnv.Clone()
env.AppendUnique(
    FRAMEWORKS = ['OpenCL','Cocoa','AppKit','Foundation', 'BWToolkitFramework'],
    FRAMEWORKPATH = ['External/BWToolkit/'])
env.Append(IBPLUGINSPATH = ['External/BWToolkit'])

interpolator = env.Program("Interpolator", Glob("*.[cm]"))

env.MacApplication(
    "Interpolator", creator = "TimH", resources = ["MainMenu.xib"],
    frameworks = ["#External/BWToolkit/BWToolkitFramework.framework"])

Return("interpolator")